from glob import glob

Import('env')

env = env.Copy(CPPPATH='#', LIBS='baseplate')

marvin = env.StaticLibrary('marvin', glob('*.[cS]'))

samba_lds = env.Command(
    'marvin_samba.lds', 'marvin.lds',
    "cat $SOURCES | sed -e 's/SAMBA_ONLY//' -e '/ROM_ONLY/d' >$TARGET")
marvin_samba_elf = env.Command(
    'marvin_samba.elf', [env['NXOS_BASEPLATE'], marvin, env['NXOS_LIBGCC']],
    '$LINK -o $TARGET -T %s -Os -Map ${TARGET}.map -cref --gc-sections $SOURCES' % samba_lds[0].path)
env.Depends(marvin_samba_elf, samba_lds)

marvin_samba = env.Command(
    'marvin_samba.bin', [marvin_samba_elf],
    '$OBJCOPY -O binary $SOURCES $TARGET')
